services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://localhost:27017/dummy
      - NODE_ENV=staging
      - JWT_SECRET=default_secret
    depends_on:
      - mongo
    networks:
      - app-network
    volumes:
      - .:/usr/src/app:delegated
      - /usr/src/app/node_modules
    restart: always

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
